=== raykyn/Python_Kursmaterial/Vertiefungsmodule/Arbeiten_mit_XML/cichlids.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="cichlids" type="cichlidsType"/>
    
    <xs:complexType name="cichlidsType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="cichlid" type="cichlidType"/>
        </xs:sequence>
        <xs:attribute name="lang" type="xs:language"/>
    </xs:complexType>
    
    <xs:complexType name="cichlidType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="color" type="xs:string"/>
            <xs:element name="teeth" type="xs:string"/>
            <xs:element name="breeding-type" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:ID"/>
    </xs:complexType>
    
</xs:schema>

=== raykyn/Python_Kursmaterial/Vertiefungsmodule/Arbeiten_mit_XML/cichlids.xml
<?xml version="1.0" encoding="UTF-8" ?>
<cichlids xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
 xsi:noNamespaceSchemaLocation="cichlids.xsd" lang="de">
    <cichlid ID="c1">
        <name>Zeus</name>
        <color>gold</color>
        <teeth>molariform</teeth>
        <breeding-type>lekking</breeding-type>
    </cichlid>
    <cichlid ID="c2">
        <name>Hera</name>
        <color>blau</color>
        <teeth>molariform</teeth>
        <breeding-type>lekking</breeding-type>
    </cichlid>
</cichlids>
